<script type="text/javascript" src="<?php echo $this->getSkinUrl('onestepcheckout/mage/opcheckout.js') ?>"></script>
<script type="text/javascript" src="<?php echo $this->getSkinUrl('onestepcheckout/opcheckout_override_mage.js') ?>"></script>
<?php //echo $this->getChildHtml("login");
$isAllowComment = Mage::getStoreConfig('lotusbreath_onestepcheckout/general/allowcomment');
$isNewsletter = Mage::getStoreConfig('lotusbreath_onestepcheckout/general/allowsubscribe');
if ($isNewsletter){
    if(Mage::getSingleton('customer/session')->isLoggedIn()){
        $subscriber = Mage::getModel('newsletter/subscriber')->loadByEmail(
            Mage::getSingleton('customer/session')->getCustomer()->getEmail());
        if($subscriber && $subscriber->getId())
        {
            $isNewsletter = false;
        }

    }
}
?>
<div class="lt-checkoutpage layout-2col " id="checkoutSteps">
    <?php echo $this->getChildHtml("loginform");?>

    <form id="checkout_form" name="checkout_form">
        <div class="grid">
            <?php if ($pageTitle = Mage::getStoreConfig('lotusbreath_onestepcheckout/content/pagetitle')):?>
            <h2 class="page-title"><?php echo $pageTitle;?></h2>
            <?php endif;?>
            <?php if ($pageDescription = Mage::getStoreConfig('lotusbreath_onestepcheckout/content/pagedescription')):?>
                <p class="page-description"><?php echo $pageDescription;?></p>
            <?php endif;?>
            <?php if (!Mage::helper('customer')->isLoggedIn()) : ?>
                <p><?php echo $this->__("Already registered? Please");?> <a href="javascript:void(0);" id="loginFrmDlgO"> <?php echo $this->__("log in");?> </a></p>
            <?php endif; ?>
            <?php if (Mage::getStoreConfig('lotusbreath_onestepcheckout/content/display_bottom_static_block')): ?>
                <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('onestepcheckout_top_block')->toHtml(); ?>
            <?php endif;?>
            <div class="row  no-padding padding-mobile">
                <div class="four columns">
                    <h3 class="ptitle">
                        <?php if ($billingHeader = Mage::getStoreConfig('lotusbreath_onestepcheckout/content/billing_header')):?>
                            <?php echo $billingHeader;?>
                        <?php else:?>
                            1. <?php echo $this->__("Billing Information"); ?>
                        <?php endif;?>

                    </h3>
                    <?php echo $this->getChildHtml('billing'); ?>
                    <div id="shipping-area" style="display: none;">
                        <h3 class="ptitle">
                            <?php if ($shippingHeader = Mage::getStoreConfig('lotusbreath_onestepcheckout/content/shipping_address_header')):?>
                                <?php echo $shippingHeader;?>
                            <?php else:?>
                                <?php echo $this->__("Shipping Information");?>
                            <?php endif;?>

                        </h3>
                        <?php
                        echo $this->getChildHtml('shipping'); ?>
                    </div>
                </div>
                <div class="eight columns">
                    <div class="row">
                        <div class="five columns">
                            <h3 class="ptitle">
                                <?php if ($shippingMethodHeader = Mage::getStoreConfig('lotusbreath_onestepcheckout/content/shipping_method_header')):?>
                                    <?php echo $shippingMethodHeader;?>
                                <?php else:?>
                                    2. <?php echo $this->__("Shipping Method"); ?>
                                <?php endif;?>
                            </h3>
                            <div id="shipping_partial">
                                <?php echo $this->getChildHtml('shipping_method'); ?>
                            </div>
                        </div>
                        <div class="seven columns">
                            <h3 class="ptitle">
                                <?php if ($paymentMethodHeader = Mage::getStoreConfig('lotusbreath_onestepcheckout/content/payment_method_header')):?>
                                    <?php echo $paymentMethodHeader;?>
                                <?php else:?>
                                    3. <?php echo $this->__("Payment Method");?>
                                <?php endif;?>

                            </h3>
                            <div id="payment_partial">
                                <?php echo $this->getChildHtml('payment'); ?>
                            </div>
                        </div>
                    </div>


                    <div class="col-3">
                        <h3 class="ptitle">
                            <?php if ($reviewOrderHeader = Mage::getStoreConfig('lotusbreath_onestepcheckout/content/review_header')):?>
                                <?php echo $reviewOrderHeader;?>
                            <?php else:?>
                                4. <?php echo $this->__("Review Order"); ?>
                            <?php endif;?>

                        </h3>

                        <div id="review_partial">
                            <?php echo $this->getData("reviewHtml"); ?>
                            <?php echo $this->getChildHtml('review'); ?>
                        </div>
                        <?php if( Mage::getStoreConfig('lotusbreath_onestepcheckout/general/allowshowgiftmessage') ):?>
                        <?php if (!$this->getQuote()->isVirtual()): ?>
                            <?php echo $this->helper('giftmessage/message')->getInline('onepage_checkout', $this->getQuote(), $this->getDontDisplayContainer()) ?>
                        <?php endif; ?>
                        <?php endif;?>
                        <?php if( Mage::getStoreConfig('lotusbreath_onestepcheckout/general/allowshowcoupon') ):?>
                            <div id="coupon_patial">
                        <h3 class="ptitle"><?php echo $this->__("Discount Codes");?></h3>

                            <?php echo $this->getChildHtml('coupon'); ?>
                        </div>
                        <?php endif;?>
                        <?php if( Mage::getStoreConfig('lotusbreath_onestepcheckout/general/allowcomment') ):?>
                        <div id="comment-patial">
                            <h3 class="ptitle"><?php echo $this->__("Comment");?></h3>
                            <ul class="form-list">
                                <li class="fields">
                                    <div class="input-box">
                                        <textarea name="order_comment" placeholder="<?php echo $this->__("Type comment here");?>" class="input-text"></textarea>
                                    </div>
                                </li>
                             </ul>
                        </div>
                        <?php endif;?>
                        <?php if ($isNewsletter):?>
                        <p class="newsletter">

                            <input type="checkbox" id="newsletter-signup" name="newsletter" value="1"
                                   title="<?php echo Mage::helper('newsletter')->__('Sign up for our newsletter') ?>"
                                   class="checkbox"
                                <?php
                                echo Mage::getStoreConfig('lotusbreath_onestepcheckout/general/autochecksubscriber') ? 'checked="checked"' : '';
                                ?>
                                />
                            <label for="newsletter-signup">
                                <?php echo Mage::helper('newsletter')->__('Sign up for our newsletter') ?>
                            </label>
                        </p>
                        <?php endif;?>
                        <?php echo $this->getChildHtml('agreements') ?>
                        <div id="saveOder-error" class="error"></div>
                        <button role='review-save' type="submit"
                                title="<?php echo Mage::helper('checkout')->__('Place Order') ?>" name="submitbtn"
                                id="lbonepage-place-order-btn" class="button btn-checkout">
                            <span><span><?php echo Mage::helper('checkout')->__('Place Order') ?></span></span>
                        </button>
                    </div>
                </div>

            </div>
            <div class="clearfix"></div>
            <?php if (Mage::getStoreConfig('lotusbreath_onestepcheckout/content/display_bottom_static_block')): ?>
            <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('onestepcheckout_bottom_block')->toHtml(); ?>
            <?php endif;?>
        </div>
    </form>


</div>
